name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  rust_toolchain: nightly-2023-03-09

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup | Identify changed projects
        run: |
          echo code_changes=$(git diff --diff-filter=ACMRT --name-only HEAD^ HEAD | grep "code/" | cut -d/ -f2 | uniq) >> $GITHUB_ENV
      - name: Setup | Rust
        if: env.code_changes >= 1
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy, rust-src
      - name: Setup | Default to nightly
        if: env.code_changes >= 1
        run: rustup default ${{ env.rust_toolchain }}
      - name: Setup | ldproxy
        if: env.code_changes >= 1
        run: cargo install ldproxy
      # Build driver itself
      - name: Build | Fmt Check
        if: env.code_changes >= 1
        working-directory: ./
        continue-on-error: true
        run: cargo fmt -- --check
      - name: Build | Clippy
        if: env.code_changes >= 1
        working-directory: ./
        continue-on-error: true
        run: cargo clippy --all-features --no-deps -- -Dwarnings
      - name: Build | Compile
        if: env.code_changes >= 1
        working-directory: ./
        run: cargo build --all-features