[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32L432KCUx with your chip as listed in `probe-run --list-chips`
runner = "probe-run --chip STM32L432KCUx"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"